site_name: shuffle-kit

repo_url: https://github.com/jmssnr/shuffle-kit

theme:
  name: "material"
  logo: logos/shuffle-kit-logo.png
  favicon: logos/shuffle-kit-logo.png
  palette:
    primary: pink
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - search.suggest

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            unwrap_annotated: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_section_style: spacy
  - search

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Getting started:
      - Installation: getting-started/installation.md
      - Contributing: getting-started/contributing.md
  - Tutorials: tutorials/index.md
  - Guides: how-to-guides.md
  - Explanations: explanation.md
  - API reference:
      - reference/models.md
      - reference/evaluate.md
