site_name: shuffle-kit

repo_url: https://github.com/jmssnr/shuffle-kit

theme:
  name: "material"
  logo: logos/shuffle-kit-logo.png
  favicon: logos/shuffle-kit-logo.png
  palette:
    primary: pink
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - search.suggest

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Getting started: index.md
  - Tutorials: tutorials.md
  - Guides: how-to-guides.md
  - Explanations: explanation.md
  - API reference: reference.md